name: Build

on:
  push:
    branches: [ master, main ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Build Plugins
        run: |
          chmod +x gradlew
          ./gradlew make makePluginsJson

      - name: Upload artifacts (optional)
        uses: actions/upload-artifact@v4
        with:
          name: plugins
          path: |
            **/build/*.cs3
            build/plugins.json
